### PR TITLE
Add Test Suite

### PR DESCRIPTION
**Pull request by iam-TJ**
A grid-template HTML page with a selection of test images and HTML
elements including img, svg, canvas, video and CSS background-image.

The ./test/ sub-directory should be excluded from publishing in the XPI.

Signed-of-by: Tj <hacker@iam.tj>

### CODE REVIEW

**Comment by Max-Github** [comment]
This is a very good addition. Just need to think about the folder structure before adding this. We might need to move the current root to a sub-folder and have the test external.

**Comment by iam-TJ** [comment]
I don't think a directory re-arrangement is necessary. When creating the XPI simply add another exclude path to the zip command, as in:

$ zip -r ../test.xpi . --exclude .gitignore .git/\* ./test/\*

updating: README.md (deflated 8%)
updating: manifest.json (deflated 58%)
updating: LICENSE (deflated 65%)
updating: options.js (deflated 74%)
updating: image.css (deflated 30%)
updating: icons/ (stored 0%)
updating: icons/off.svg (deflated 70%)
updating: icons/on.svg (deflated 77%)
updating: style.css (deflated 38%)
updating: background.js (deflated 77%)
updating: options.html (deflated 53%)

**Comment by Max-Github** [comment]
I have moved the source code to a separate folder. It really should have been in a dedicated sub folder from the start. 

Let me know if you want to do any changes to the test PR before it is accepted.

**Comment by iam-TJ** [comment]
I think it's OK as-is; I did try to add some tests for the Firefox positioning bug but gave up on that as a bad job and not worth the effort! There may be additional tests to add later for some very complicated deep hierarchies I see on http://www.bbc.co.uk/news/  in some rare circumstances but have been unable to reproduce manually so far (I suspect BBC Javascript is playing tricks!).

This PR branch is self-contained in ./test/ so shouldn't conflict with moving source-code.

**Pull request merged**
